in_images:
  T1w:
    '001':
    - entities:
        datatype: anat
        extension: nii.gz
        subject: '001'
        suffix: T1w
      path: /Users/alik/work/src/snakebids-app/bids/sub-001/anat/sub-001_T1w.nii.gz
  T2w:
    '001': []
  dwi:
    '001':
    - entities:
        datatype: dwi
        extension: nii.gz
        subject: '001'
        suffix: dwi
      path: /Users/alik/work/src/snakebids-app/bids/sub-001/dwi/sub-001_dwi.nii.gz
search_terms:
  T1w:
    suffix: T1w
  T2w:
    suffix: T2w
  dwi:
    suffix: dwi
sessions: null
subjects:
- '001'
zip_sessions:
  T1w: []
  T2w: []
  dwi: []
zip_subjects:
  T1w:
  - '001'
  T2w:
  - '001'
  dwi:
  - '001'
